// Generated by https://quicktype.io

export interface IUser {
    id:         number;
    username:   string;
    email:      string;
    first_name: string;
    last_name:  string;
    groups:     IUserGroup[];
}

export interface IUserGroup {
    id:          number;
    name:        string;
    permissions: any[];
}
